services:
  - type: web
    name: stalker-pda-bot
    env: python
    buildCommand: ""
    startCommand: python bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
